# Generated by Django 5.1.7 on 2025-03-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oil', '0003_contact_address_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='oilproduct',
            name='category',
            field=models.CharField(choices=[('Groundnut', 'Groundnut'), ('Mustard', 'Mustard'), ('Sunflower', 'Sunflower')], default='Groundnut', max_length=50),
        ),
        migrations.AlterField(
            model_name='oilproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='oilproduct',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
