# Generated by Django 5.1.7 on 2025-03-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oil', '0005_contactmessage_delete_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='oilproduct',
            name='description',
        ),
        migrations.AddField(
            model_name='oilproduct',
            name='category',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='category',
            field=models.CharField(default='Groundnut', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2500, max_digits=10),
        ),
    ]
